POST https://gym-login-database.onrender.com/login389212
Content-Type: application/json

{
    "email": "caiogsan@hotmail.com",
    "username": "caiogsan",
    "password": "123456789"
}

###

GET https://gym-login-database.onrender.com/login389212

###